### ISSUE TITLE
unable to claim some trailers

### ISSUE THREAD

**Issue by SG-JoozBrorg** [Lu5ck/AnotherVehicleClaimSystem#2]
![adcl](https://github.com/Lu5ck/AnotherVehicleClaimSystem/assets/75929451/4efbe701-d340-410a-9caa-5e303275b41c)
 
 Image shows to contact admin ect do we need to set this to be allowed in the files?

**Comment by Lu5ck** [comment]
Read the [explanations](https://steamcommunity.com/workshop/filedetails/discussion/2957935793/3826412338730020081/)

You have to determine the mule part for your mod vehicles
